/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica3;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.ArrayList;

/**
 *
 * @author mmnuria
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Point punto = new Point(-100,-100);
    private Point inicioLinea = null;
    private Point finLinea = null;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(700,700);
        // Agregar eventos del mouse a toda la ventana
        
    }
    @Override //ponerlo siempre
    public void paint(Graphics g) {
        super.paint(g); //haz lo que tenia el padre y ahora me añades el resto
        g.setColor(Color.BLACK);

        // Dibujar puntos
        g.fillOval(punto.x, punto.y, 6, 6);

        // Dibujar línea en tiempo real
        if (inicioLinea != null && finLinea != null) {
            g.setColor(Color.RED);
            g.drawLine(inicioLinea.x, inicioLinea.y, finLinea.x, finLinea.y);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(formListener);
        addMouseListener(formListener);
        getContentPane().setLayout(new java.awt.FlowLayout());

        boton.setText("Boton 1");
        boton.addMouseMotionListener(formListener);
        boton.addMouseListener(formListener);
        getContentPane().add(boton);

        boton2.setText("Boton 2");
        boton2.addMouseListener(formListener);
        boton2.addActionListener(formListener);
        getContentPane().add(boton2);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == boton2) {
                VentanaPrincipal.this.boton2ActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton) {
                VentanaPrincipal.this.botonMouseClicked(evt);
            }
            else if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseClicked(evt);
            }
            else if (evt.getSource() == boton2) {
                VentanaPrincipal.this.boton2MouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton) {
                VentanaPrincipal.this.botonMouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton) {
                VentanaPrincipal.this.botonMouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseReleased(evt);
            }
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton) {
                VentanaPrincipal.this.botonMouseDragged(evt);
            }
            else if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
        this.boton.setBackground(Color.red);      
    }//GEN-LAST:event_botonMouseClicked

    private void botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseEntered
        this.boton.setBackground(Color.BLUE);       
    }//GEN-LAST:event_botonMouseEntered

    private void botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseExited
        this.boton.setBackground(Color.green);
    }//GEN-LAST:event_botonMouseExited

    private void botonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseDragged
        this.boton.setBackground(Color.pink);
    }//GEN-LAST:event_botonMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.setTitle("Se ha clicado la ventana"); 
        
        punto = evt.getPoint(); // Agregar punto al hacer clic
        this.repaint();
    }//GEN-LAST:event_formMouseClicked

    private void boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseClicked
        this.boton2.setBackground(Color.YELLOW);        
    }//GEN-LAST:event_boton2MouseClicked

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        this.boton2.setBackground(Color.MAGENTA); //este es el que se usa mas que el clicked, para que si le das con cualquier tecla reaccione
    }//GEN-LAST:event_boton2ActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        finLinea = evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        finLinea = evt.getPoint(); // Actualiza la posición final de la línea mientras se arrastra
        repaint();
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        inicioLinea = evt.getPoint();
    }//GEN-LAST:event_formMousePressed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JButton boton2;
    // End of variables declaration//GEN-END:variables
}
