/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica5.pkgfinal;

import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mmnuria
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(700,700);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        buttonLinea = new javax.swing.JToggleButton();
        buttonRectangulo = new javax.swing.JToggleButton();
        buttonElipse = new javax.swing.JToggleButton();
        PanelSur = new javax.swing.JPanel();
        buttonNegro = new javax.swing.JButton();
        buttonRojo = new javax.swing.JButton();
        buttonAmarillo = new javax.swing.JButton();
        buttonAzul = new javax.swing.JButton();
        buttonVerde = new javax.swing.JButton();
        buttonBlanco = new javax.swing.JButton();
        checkBoxRelleno = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        LabelBarraDeEstado = new javax.swing.JLabel();
        lienzo = new practica5.pkgfinal.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        ItemNuevo = new javax.swing.JMenuItem();
        ItemAbrir = new javax.swing.JMenuItem();
        ItemGuardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        buttonGroup1.add(buttonLinea);
        buttonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/linea.png"))); // NOI18N
        buttonLinea.setSelected(true);
        buttonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLineaActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonLinea);
        buttonLinea.getAccessibleContext().setAccessibleDescription("");

        buttonGroup1.add(buttonRectangulo);
        buttonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rectangulo.png"))); // NOI18N
        buttonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRectanguloActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonRectangulo);
        buttonRectangulo.getAccessibleContext().setAccessibleDescription("");

        buttonGroup1.add(buttonElipse);
        buttonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/elipse.png"))); // NOI18N
        buttonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElipseActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonElipse);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        buttonNegro.setBackground(new java.awt.Color(0, 0, 0));
        buttonNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNegroMouseClicked(evt);
            }
        });
        buttonNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNegroActionPerformed(evt);
            }
        });

        buttonRojo.setBackground(new java.awt.Color(255, 0, 0));
        buttonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRojoActionPerformed(evt);
            }
        });

        buttonAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        buttonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAmarilloActionPerformed(evt);
            }
        });

        buttonAzul.setBackground(new java.awt.Color(0, 0, 255));
        buttonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAzulActionPerformed(evt);
            }
        });

        buttonVerde.setBackground(new java.awt.Color(51, 255, 0));
        buttonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerdeActionPerformed(evt);
            }
        });

        buttonBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBlancoActionPerformed(evt);
            }
        });

        checkBoxRelleno.setText("Relleno");
        checkBoxRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxRellenoActionPerformed(evt);
            }
        });

        LabelBarraDeEstado.setText("Barra de estado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBarraDeEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelBarraDeEstado))
        );

        javax.swing.GroupLayout PanelSurLayout = new javax.swing.GroupLayout(PanelSur);
        PanelSur.setLayout(PanelSurLayout);
        PanelSurLayout.setHorizontalGroup(
            PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(buttonNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                .addComponent(checkBoxRelleno)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelSurLayout.setVerticalGroup(
            PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSurLayout.createSequentialGroup()
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSurLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(checkBoxRelleno))
                    .addGroup(PanelSurLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonAzul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRojo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonNegro, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                            .addComponent(buttonVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelSur, java.awt.BorderLayout.PAGE_END);

        lienzo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        ItemNuevo.setText("Nuevo");
        ItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(ItemNuevo);

        ItemAbrir.setText("Abrir");
        ItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(ItemAbrir);

        ItemGuardar.setText("Guardar");
        menuArchivo.add(ItemGuardar);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNegroMouseClicked
        
    }//GEN-LAST:event_buttonNegroMouseClicked

    private void buttonNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNegroActionPerformed

        lienzo.setColor(Color.BLACK);
        LabelBarraDeEstado.setText("Color negro seleccionado");
    }//GEN-LAST:event_buttonNegroActionPerformed

    private void buttonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRojoActionPerformed
        lienzo.setColor(Color.red);
        LabelBarraDeEstado.setText("Color rojo seleccionado");
    }//GEN-LAST:event_buttonRojoActionPerformed

    private void buttonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAmarilloActionPerformed
        lienzo.setColor(Color.yellow);
        LabelBarraDeEstado.setText("Color amarillo seleccionado");
    }//GEN-LAST:event_buttonAmarilloActionPerformed

    private void buttonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAzulActionPerformed
        lienzo.setColor(Color.blue);
        LabelBarraDeEstado.setText("Color azul seleccionado");
    }//GEN-LAST:event_buttonAzulActionPerformed

    private void buttonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerdeActionPerformed
        lienzo.setColor(Color.green);
        LabelBarraDeEstado.setText("Color verde seleccionado");
    }//GEN-LAST:event_buttonVerdeActionPerformed

    private void buttonBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBlancoActionPerformed
        lienzo.setColor(Color.white);
        LabelBarraDeEstado.setText("Color blanco seleccionado");
    }//GEN-LAST:event_buttonBlancoActionPerformed

    private void checkBoxRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxRellenoActionPerformed
        lienzo.setRelleno(checkBoxRelleno.isSelected());
        LabelBarraDeEstado.setText("Relleno");
    }//GEN-LAST:event_checkBoxRellenoActionPerformed

    private void buttonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLineaActionPerformed
        lienzo.setHerramientaDibujo(Lienzo.HerramientaDibujo.linea);
        LabelBarraDeEstado.setText("Linea");
    }//GEN-LAST:event_buttonLineaActionPerformed

    private void buttonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRectanguloActionPerformed
        lienzo.setHerramientaDibujo(Lienzo.HerramientaDibujo.rectangulo);
        LabelBarraDeEstado.setText("Rectangulo");
    }//GEN-LAST:event_buttonRectanguloActionPerformed

    private void buttonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElipseActionPerformed
        lienzo.setHerramientaDibujo(Lienzo.HerramientaDibujo.elipse);
        LabelBarraDeEstado.setText("Elipse");
    }//GEN-LAST:event_buttonElipseActionPerformed

    private void ItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNuevoActionPerformed
        
    }//GEN-LAST:event_ItemNuevoActionPerformed

    private void ItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAbrirActionPerformed
        // Mostrar diálogo de apertura (sin abrir archivos)
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "Archivo seleccionado: " + fileChooser.getSelectedFile().getName());
        }
        LabelBarraDeEstado.setText("Abrir");
    }//GEN-LAST:event_ItemAbrirActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAbrir;
    private javax.swing.JMenuItem ItemGuardar;
    private javax.swing.JMenuItem ItemNuevo;
    private javax.swing.JLabel LabelBarraDeEstado;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JButton buttonAmarillo;
    private javax.swing.JButton buttonAzul;
    private javax.swing.JButton buttonBlanco;
    private javax.swing.JToggleButton buttonElipse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton buttonLinea;
    private javax.swing.JButton buttonNegro;
    private javax.swing.JToggleButton buttonRectangulo;
    private javax.swing.JButton buttonRojo;
    private javax.swing.JButton buttonVerde;
    private javax.swing.JCheckBox checkBoxRelleno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    private practica5.pkgfinal.Lienzo lienzo;
    private javax.swing.JMenu menuArchivo;
    // End of variables declaration//GEN-END:variables
}
