/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica7;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import sm.nmm.graficos.NHerramientaDibujo;

/**
 *
 * @author mmnuria
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(700,700);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        buttonLinea = new javax.swing.JToggleButton();
        buttonRectangulo = new javax.swing.JToggleButton();
        buttonElipse = new javax.swing.JToggleButton();
        buttonCurva = new javax.swing.JToggleButton();
        buttonSeleccion = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        panelColor = new javax.swing.JPanel();
        buttonColor = new javax.swing.JButton();
        buttonRellenar = new javax.swing.JToggleButton();
        buttonTransparencia = new javax.swing.JToggleButton();
        buttonAlisar = new javax.swing.JToggleButton();
        slider = new javax.swing.JSlider();
        PanelSur = new javax.swing.JPanel();
        panelBarraEstado = new javax.swing.JPanel();
        LabelBarraDeEstado = new javax.swing.JLabel();
        lienzo2D = new sm.nmm.iu.Lienzo2D();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        ItemNuevo = new javax.swing.JMenuItem();
        ItemAbrir = new javax.swing.JMenuItem();
        ItemGuardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        buttonGroup1.add(buttonLinea);
        buttonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/linea.png"))); // NOI18N
        buttonLinea.setSelected(true);
        buttonLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLineaActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonLinea);
        buttonLinea.getAccessibleContext().setAccessibleDescription("");

        buttonGroup1.add(buttonRectangulo);
        buttonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rectangulo.png"))); // NOI18N
        buttonRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRectanguloActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonRectangulo);
        buttonRectangulo.getAccessibleContext().setAccessibleDescription("");

        buttonGroup1.add(buttonElipse);
        buttonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/elipse.png"))); // NOI18N
        buttonElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElipseActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonElipse);

        buttonGroup1.add(buttonCurva);
        buttonCurva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/curva.png"))); // NOI18N
        buttonCurva.setFocusable(false);
        buttonCurva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCurva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonCurva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCurvaActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonCurva);

        buttonGroup1.add(buttonSeleccion);
        buttonSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/seleccion.png"))); // NOI18N
        buttonSeleccion.setFocusable(false);
        buttonSeleccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSeleccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeleccionActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonSeleccion);
        jToolBar1.add(jSeparator1);

        panelColor.setMaximumSize(new java.awt.Dimension(30, 30));
        panelColor.setPreferredSize(new java.awt.Dimension(30, 30));
        panelColor.setLayout(new java.awt.BorderLayout());

        buttonColor.setBackground(new java.awt.Color(0, 0, 0));
        buttonColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonColor.setMaximumSize(new java.awt.Dimension(25, 25));
        buttonColor.setMinimumSize(new java.awt.Dimension(20, 20));
        buttonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColorActionPerformed(evt);
            }
        });
        panelColor.add(buttonColor, java.awt.BorderLayout.CENTER);

        jToolBar1.add(panelColor);

        buttonRellenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rellenar.png"))); // NOI18N
        buttonRellenar.setFocusable(false);
        buttonRellenar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonRellenar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonRellenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRellenarActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonRellenar);

        buttonTransparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/transparencia.png"))); // NOI18N
        buttonTransparencia.setFocusable(false);
        buttonTransparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTransparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransparenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonTransparencia);

        buttonAlisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/alisar.png"))); // NOI18N
        buttonAlisar.setFocusable(false);
        buttonAlisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAlisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAlisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlisarActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonAlisar);

        slider.setMinimum(1);
        slider.setSnapToTicks(true);
        slider.setValue(1);
        slider.setMaximumSize(new java.awt.Dimension(20, 20));
        slider.setPreferredSize(new java.awt.Dimension(50, 50));
        slider.setSize(new java.awt.Dimension(100, 20));
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        jToolBar1.add(slider);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        PanelSur.setLayout(new java.awt.BorderLayout());

        LabelBarraDeEstado.setText("Barra de estado");

        javax.swing.GroupLayout panelBarraEstadoLayout = new javax.swing.GroupLayout(panelBarraEstado);
        panelBarraEstado.setLayout(panelBarraEstadoLayout);
        panelBarraEstadoLayout.setHorizontalGroup(
            panelBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBarraDeEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarraEstadoLayout.setVerticalGroup(
            panelBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraEstadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelBarraDeEstado))
        );

        PanelSur.add(panelBarraEstado, java.awt.BorderLayout.SOUTH);

        getContentPane().add(PanelSur, java.awt.BorderLayout.PAGE_END);

        lienzo2D.setBackground(new java.awt.Color(255, 255, 255));
        lienzo2D.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo2D, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        ItemNuevo.setText("Nuevo");
        ItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(ItemNuevo);

        ItemAbrir.setText("Abrir");
        ItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(ItemAbrir);

        ItemGuardar.setText("Guardar");
        menuArchivo.add(ItemGuardar);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLineaActionPerformed
        lienzo2D.setHerramientaDibujo(NHerramientaDibujo.linea);
        LabelBarraDeEstado.setText("Linea");
    }//GEN-LAST:event_buttonLineaActionPerformed

    private void buttonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRectanguloActionPerformed
        lienzo2D.setHerramientaDibujo(NHerramientaDibujo.rectangulo);
        LabelBarraDeEstado.setText("Rectangulo");
    }//GEN-LAST:event_buttonRectanguloActionPerformed

    private void buttonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElipseActionPerformed
        lienzo2D.setHerramientaDibujo(NHerramientaDibujo.elipse);
        LabelBarraDeEstado.setText("Elipse");
    }//GEN-LAST:event_buttonElipseActionPerformed

    private void ItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNuevoActionPerformed
        
    }//GEN-LAST:event_ItemNuevoActionPerformed

    private void ItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAbrirActionPerformed
        // Mostrar diálogo de apertura (sin abrir archivos)
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "Archivo seleccionado: " + fileChooser.getSelectedFile().getName());
        }
        LabelBarraDeEstado.setText("Abrir");
    }//GEN-LAST:event_ItemAbrirActionPerformed

    private void buttonCurvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCurvaActionPerformed
        lienzo2D.setHerramientaDibujo(NHerramientaDibujo.curva);
        LabelBarraDeEstado.setText("Curva");
    }//GEN-LAST:event_buttonCurvaActionPerformed

    private void buttonSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeleccionActionPerformed
        lienzo2D.setMover(buttonSeleccion.isSelected()); 
        System.out.println("MOVER" + buttonSeleccion.isSelected());
        LabelBarraDeEstado.setText("Mover");
    }//GEN-LAST:event_buttonSeleccionActionPerformed

    private void buttonRellenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRellenarActionPerformed
        lienzo2D.setRelleno(buttonRellenar.isSelected());
        LabelBarraDeEstado.setText("Relleno");
    }//GEN-LAST:event_buttonRellenarActionPerformed

    private void buttonTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransparenciaActionPerformed
        lienzo2D.setTransparencia(buttonTransparencia.isSelected());
        LabelBarraDeEstado.setText("Transparencia");
    }//GEN-LAST:event_buttonTransparenciaActionPerformed

    private void buttonAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlisarActionPerformed
        lienzo2D.setAlisar(buttonAlisar.isSelected());
        LabelBarraDeEstado.setText("Alisado");
    }//GEN-LAST:event_buttonAlisarActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        int grosor = (int) slider.getValue();
        lienzo2D.setGrosorTrazo(grosor);
        LabelBarraDeEstado.setText("Cambio de grosor");
    }//GEN-LAST:event_sliderStateChanged

    private void buttonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColorActionPerformed
        Color color = JColorChooser.showDialog(this, "Elige un color", Color.red);
        lienzo2D.setColor(color);
        buttonColor.setBackground(color);
    }//GEN-LAST:event_buttonColorActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAbrir;
    private javax.swing.JMenuItem ItemGuardar;
    private javax.swing.JMenuItem ItemNuevo;
    private javax.swing.JLabel LabelBarraDeEstado;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JToggleButton buttonAlisar;
    private javax.swing.JButton buttonColor;
    private javax.swing.JToggleButton buttonCurva;
    private javax.swing.JToggleButton buttonElipse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton buttonLinea;
    private javax.swing.JToggleButton buttonRectangulo;
    private javax.swing.JToggleButton buttonRellenar;
    private javax.swing.JToggleButton buttonSeleccion;
    private javax.swing.JToggleButton buttonTransparencia;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private sm.nmm.iu.Lienzo2D lienzo2D;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JPanel panelBarraEstado;
    private javax.swing.JPanel panelColor;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
}
