/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practica14;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.util.Iterator;
import sm.nmm.graficos.NShape;
import sm.nmm.iu.Lienzo2D;

/**
 *
 * @author mmnuria
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna() {
        initComponents();
    }

    public Lienzo2D getLienzo2D() {
        return lienzo;
    }

    /*private VentanaInterna getSelectedVentana() {
        VentanaInterna vi;
        return vi = (VentanaInterna) escritorio.getSelectedFrame();
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new sm.nmm.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzoMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseMoved

        if (lienzo != null) {
            if (lienzo.getModoFijar() || lienzo.getModoEliminar()) {
                Iterator<NShape> it = lienzo.getShapeList().iterator();
                while (it.hasNext()) {
                    NShape s = it.next();
                    if (s.contains(evt.getPoint())) {

                        if (lienzo.getModoFijar()) {
                            BufferedImage imagen = lienzo.getImage();
                            if (imagen != null) {
                                Graphics2D g2 = imagen.createGraphics();
                                s.draw(g2);
                                g2.dispose();
                            }

                            if (lienzo.getSonidoFijar() != null) {
                                lienzo.play(lienzo.getSonidoFijar());
                            }

                            it.remove();
                            lienzo.repaint();

                        } else if (lienzo.getModoEliminar()) {

                            if (lienzo.getSonidoEliminar() != null) {
                                lienzo.play(lienzo.getSonidoEliminar());
                            }

                            it.remove();
                            lienzo.repaint();
                        }

                        break;
                    }
                }
            }
        }

    }//GEN-LAST:event_lienzoMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.nmm.iu.Lienzo2D lienzo;
    // End of variables declaration//GEN-END:variables

}
